### ISSUE TITLE
Tidak bisa digunakan kembali pada saat XL menggunakan MyXL terbaru

### ISSUE THREAD

**Issue by rapdodge** [adipatiarya/XLRequest#1]
XL sekarang menggunakan login baru menggunakan SMS Token, mohon untuk menyesuaikannya kembali :D

**Comment by adipatiarya** [comment]
Sabar ini ujian :v:  tunggu semingguan lg

**Comment by rapdodge** [comment]
Sekarang menggunakan OTP SMS gan...

**Comment by A710140033** [comment]
XL Go Izi masih bisa ditembak gak gan?

**Comment by crosshold408** [comment]
katanya bisa lagi tapi ane gatau,, min tembakin dong

**Comment by anang2909** [comment]
izi bisa tp sistem buka tutup.. gmn nih???

**Comment by javierxz** [comment]
Ditunggu updatenya mbah.

**Comment by ghofur27** [comment]
xl izi koid lagi gan

**Comment by rapdodge** [comment]
@adipatiarya diupdate dong source code nya :D

**Comment by adipatiarya** [comment]
Closed all
